import {test,expect} from '@playwright/test';

const base='http://127.0.0.1:5055';
const reset=()=>fetch(`${base}/reset`,{method:'POST'});
const change=operation=>fetch(`${base}/changes`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(operation)}).then(r=>r.json());
const create=(recordId='r1',data={title:'Train',startTime:'09:00',location:'Station X'})=>change({operationId:`create-${recordId}`,tripId:'trip-italy-2026',recordType:'AGENDA_ENTRY',recordId,action:'CREATE',baseVersion:0,changes:data,userId:'seed',deviceId:'seed-device',createdAt:new Date().toISOString()});
const update=(operationId,recordId,baseVersion,changes,userId='a')=>change({operationId,tripId:'trip-italy-2026',recordType:'AGENDA_ENTRY',recordId,action:'UPDATE',baseVersion,changes,userId,deviceId:`device-${userId}`,createdAt:new Date().toISOString()});

test.beforeEach(async()=>{await reset()});

test('canonical create, current update, version history and idempotency',async()=>{expect((await create()).canonical.version).toBe(1);const op={operationId:'update-1',tripId:'trip-italy-2026',recordType:'AGENDA_ENTRY',recordId:'r1',action:'UPDATE',baseVersion:1,changes:{startTime:'10:00'},userId:'a',deviceId:'da',createdAt:new Date().toISOString()};const first=await change(op),second=await change(op);expect(first).toMatchObject({status:'APPLIED',canonical:{version:2}});expect(second).toMatchObject({status:'DUPLICATE',canonical:{version:2}});expect((await fetch(`${base}/records/r1`).then(r=>r.json())).version).toBe(2);});

test('stale different fields merge regardless of reconnect order',async()=>{await create();const a=await update('a-1','r1',1,{startTime:'10:00'},'a');const b=await update('b-1','r1',1,{location:'Station Y'},'b');expect(a.status).toBe('APPLIED');expect(b.status).toBe('APPLIED');expect((await fetch(`${base}/records/r1`).then(r=>r.json())).data).toMatchObject({startTime:'10:00',location:'Station Y'});await reset();await create();expect((await update('b-2','r1',1,{location:'Station Y'},'b')).status).toBe('APPLIED');expect((await update('a-2','r1',1,{startTime:'10:00'},'a')).status).toBe('APPLIED');expect((await fetch(`${base}/records/r1`).then(r=>r.json())).data).toMatchObject({startTime:'10:00',location:'Station Y'});});

test('same value is compatible and different same-field update creates conflict',async()=>{await create();await update('a-3','r1',1,{startTime:'10:00'},'a');const same=await update('b-3','r1',1,{startTime:'10:00'},'b');expect(same.status).toBe('APPLIED');expect(same.canonical.version).toBe(2);const conflict=await update('c-3','r1',1,{startTime:'11:00'},'c');expect(conflict).toMatchObject({status:'CONFLICT',conflict:{type:'SAME_FIELD_CONFLICT',field:'startTime',baseValue:'09:00',currentValue:'10:00',incomingValue:'11:00'}});expect(await fetch(`${base}/conflicts?tripId=trip-italy-2026`).then(r=>r.json())).toHaveLength(1);});

test('delete tombstone wins over stale edit and stale create cannot resurrect',async()=>{await create('r-delete');const deleted=await change({operationId:'delete-1',tripId:'trip-italy-2026',recordType:'AGENDA_ENTRY',recordId:'r-delete',action:'DELETE',baseVersion:1,changes:{},userId:'a',deviceId:'da',createdAt:new Date().toISOString()});expect(deleted.canonical.deletedAt).toBeTruthy();const stale=await update('edit-after-delete','r-delete',1,{title:'Resurrected'},'b');expect(stale).toMatchObject({status:'CONFLICT',conflict:{type:'DELETE_VS_EDIT'}});const recreate=await change({operationId:'create-after-delete',tripId:'trip-italy-2026',recordType:'AGENDA_ENTRY',recordId:'r-delete',action:'CREATE',baseVersion:1,changes:{title:'Resurrected'},userId:'b',deviceId:'db',createdAt:new Date().toISOString()});expect(recreate.status).toBe('REJECTED_TOMBSTONE');expect((await fetch(`${base}/records/r-delete`).then(r=>r.json())).deletedAt).toBeTruthy();});

test('two browser contexts pull canonical records',async({browser})=>{const a=await browser.newContext(),b=await browser.newContext();const pa=await a.newPage(),pb=await b.newPage();try{await pa.goto('/');await pb.goto('/');await create('r-e2e');const result=await pa.evaluate(async()=>{const adapter=new (await import('/src/services/remoteSyncAdapter.js')).MockRemoteSyncAdapter();return adapter.pushOperations([{operationId:'e2e-a',tripId:'trip-italy-2026',recordType:'AGENDA_ENTRY',recordId:'r-e2e',action:'UPDATE',baseVersion:1,changes:{startTime:'10:00'},userId:'a',deviceId:'da',createdAt:new Date().toISOString()}])});expect(result[0].status).toBe('APPLIED');const pulled=await pb.evaluate(async()=>{const adapter=new (await import('/src/services/remoteSyncAdapter.js')).MockRemoteSyncAdapter();return adapter.pullRecords({tripId:'trip-italy-2026',sinceVersion:0})});expect(pulled.find(x=>x.recordId==='r-e2e').data.startTime).toBe('10:00');}finally{await a.close();await b.close();}});
