import {test,expect} from '@playwright/test';

const trip='trip-chat-e2e';
async function reset(request){await request.post('http://127.0.0.1:5055/reset');}
async function context(browser,userId,userName,deviceId){return browser.newContext({storageState:{origins:[{origin:'http://127.0.0.1:5003',localStorage:[{name:'agenda-viajera.user',value:userId},{name:'agenda-viajera.userName',value:userName},{name:'agenda-viajera.device',value:deviceId},{name:'agenda-viajera.deviceState',value:'TRUSTED'}]}]}})}
async function openChat(page){await page.goto('/');await page.getByRole('button',{name:'Chat'}).click();await expect(page.getByRole('heading',{name:'Chat del viaje'})).toBeVisible();}
async function openDirect(page){await page.getByRole('button',{name:'Directos'}).click();await expect(page.locator('[data-chat-ready="true"]')).toBeVisible();}
async function send(page,text,count){const input=page.getByLabel('Mensaje');await expect(input).toBeVisible();await input.fill(text);await page.getByRole('button',{name:'Enviar'}).click();await expect(page.locator('.chat-bubble')).toHaveCount(count);await expect(input).toBeVisible();}
async function pull(page){await page.reload();await page.getByRole('button',{name:'Chat'}).click();}

test('group chat crosses isolated browser contexts in both directions',async({browser,request})=>{await reset(request);const a=await context(browser,'a','A','device-a'),b=await context(browser,'b','B','device-b');const pa=await a.newPage(),pb=await b.newPage();try{await openChat(pa);await send(pa,'Hola desde A',1);await expect(pa.getByText('Enviado')).toBeVisible();await openChat(pb);await expect(pb.getByText('Hola desde A')).toBeVisible();await send(pb,'Hola desde B',2);await pull(pa);await expect(pa.getByText('Hola desde B')).toBeVisible();await expect(pa.locator('.chat-bubble')).toHaveCount(2);}finally{await a.close();await b.close();}});

test('offline batch reconnects to the second context without duplicates',async({browser,request})=>{await reset(request);const a=await context(browser,'a','A','device-a2'),b=await context(browser,'b','B','device-b2');const pa=await a.newPage(),pb=await b.newPage();try{await openChat(pa);await a.setOffline(true);await expect.poll(()=>pa.evaluate(()=>navigator.onLine),{timeout:5000}).toBe(false);let count=0;for(const text of ['Offline 1','Offline 2','Offline 3'])await send(pa,text,++count);await expect(pa.getByText('Pendiente')).toHaveCount(3);await openChat(pb);await expect(pb.getByText('Offline 1')).toHaveCount(0);await a.setOffline(false);await expect.poll(()=>pa.evaluate(()=>navigator.onLine),{timeout:5000}).toBe(true);await pa.evaluate(()=>window.__tm3Chat.syncPendingMessages());await expect(pa.getByTestId('message-status')).toHaveCount(3);await expect(pa.getByText('Enviado')).toHaveCount(3);await pull(pb);await expect(pb.getByText('Offline 1')).toHaveCount(1);await pull(pa);for(const text of ['Offline 1','Offline 2','Offline 3'])await expect(pa.getByText(text)).toHaveCount(1);}finally{await a.setOffline(false).catch(()=>{});await b.setOffline(false).catch(()=>{});await pa.close().catch(()=>{});await pb.close().catch(()=>{});await a.close().catch(()=>{});await b.close().catch(()=>{});}});

test('direct conversation is ready before send',async({browser,request})=>{await reset(request);const a=await context(browser,'a','A','device-ready');const page=await a.newPage();try{await openChat(page);await openDirect(page);const state=await page.evaluate(()=>({type:window.__tm3AppState.activeConversation.type,conversationId:window.__tm3AppState.activeConversation.conversationId,recipientUserId:window.__tm3AppState.activeConversation.recipientUserId,ready:window.__tm3AppState.chatConversationReady}));expect(state).toEqual({type:'DIRECT',conversationId:'direct:trip-italy-2026:a:b',recipientUserId:'b',ready:true});await send(page,'Ready direct',1);}finally{await a.close();}});

test('direct chat is visible only to its two participants',async({browser,request})=>{await reset(request);const a=await context(browser,'a','A','device-da'),b=await context(browser,'b','B','device-db'),c=await context(browser,'c','C','device-dc');const pa=await a.newPage(),pb=await b.newPage(),pc=await c.newPage();try{await openChat(pa);await openDirect(pa);await send(pa,'Privado AB',1);await openChat(pb);await openDirect(pb);await expect(pb.getByText('Privado AB')).toBeVisible();await send(pb,'Respuesta BA',2);await pull(pa);await openDirect(pa);await expect(pa.getByText('Respuesta BA')).toBeVisible();await openChat(pc);await openDirect(pc);await expect(pc.getByText('Privado AB')).toHaveCount(0);await expect(pc.getByText('Respuesta BA')).toHaveCount(0);}finally{await a.close();await b.close();await c.close();}});
