import {test,expect} from '@playwright/test';
import {audit,auditNightCoverage} from '../public/src/services/audit.js';

test('lodging gaps resolve with lodging or overnight flight coverage',()=>{const base={tripStart:'2026-10-20',tripEnd:'2026-10-23',items:[{id:'in',type:'LODGING',checkIn:'2026-10-20',checkOut:'2026-10-21'},{id:'out',type:'LODGING',checkIn:'2026-10-22',checkOut:'2026-10-23'}]};expect(auditNightCoverage(base).map(x=>x.nightDate)).toEqual(['2026-10-21']);expect(auditNightCoverage({...base,items:[...base.items,{id:'fix',type:'LODGING',checkIn:'2026-10-21',checkOut:'2026-10-22'}]})).toHaveLength(0);expect(auditNightCoverage({...base,items:[...base.items,{id:'flight',type:'FLIGHT',startsAt:'2026-10-21T22:00:00Z',endsAt:'2026-10-22T08:00:00Z'}]})).toHaveLength(0);});
test('italy fixture covers every night',()=>{const stays=[['2026-10-20','2026-10-21'],['2026-10-21','2026-10-24'],['2026-10-24','2026-10-26'],['2026-10-26','2026-10-27'],['2026-10-27','2026-10-28'],['2026-10-28','2026-11-02'],['2026-11-02','2026-11-05']].map(([checkIn,checkOut],i)=>({id:`stay-${i}`,type:'LODGING',checkIn,checkOut}));expect(auditNightCoverage({tripStart:'2026-10-20',tripEnd:'2026-11-05',items:[...stays,{id:'outbound',type:'FLIGHT',startsAt:'2026-10-20T20:00:00Z',endsAt:'2026-10-21T10:00:00Z'}]})).toHaveLength(0);});

test('passenger documentation issue resolves after second traveler',()=>{const item={id:'flight',tripId:'t',status:'AGENDA',expectedTravelers:2};expect(audit({items:[item],travelers:[{entryId:'flight',travelerId:'a'}]}).some(x=>x.code==='MISSING_TRAVELER_DOCUMENTATION')).toBe(true);expect(audit({items:[item],travelers:[{entryId:'flight',travelerId:'a'},{entryId:'flight',travelerId:'b'}]}).some(x=>x.code==='MISSING_TRAVELER_DOCUMENTATION')).toBe(false);});

test('budget line navigates to exact agenda entry',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'J'}).click();await page.getByText('Presupuesto').click();const line=page.locator('.budget-line').first(),id=await line.getAttribute('data-entry-id');await line.getByRole('button',{name:'Ver en Agenda'}).click();await expect(page.locator('h2')).toHaveText('Agenda');await expect(page.locator(`article.item[data-entry-id="${id}"]`)).toBeVisible();});

test('audit and render calculations stay responsive at fixture scale',async({page})=>{const bootStart=performance.now();await page.goto('/');await expect(page.locator('#app')).toBeVisible();const boot_ms=Math.max(1,Math.round(performance.now()-bootStart));test.info().annotations.push({type:'performance',description:`boot_ms=${boot_ms}`});const result=await page.evaluate(async()=>{const [{audit},{calculateTripBudget},{renderChat},{renderDocuments},{renderAdmin}]=await Promise.all([import('/src/services/audit.js'),import('/src/services/budget.js'),import('/src/app/render/renderChat.js'),import('/src/app/render/renderDocuments.js'),import('/src/app/render/renderAdmin.js')]);const items=Array.from({length:100},(_,i)=>({id:`e${i}`,tripId:'t',status:'AGENDA',title:`Entry ${i}`,amount:10,date:'2026-10-20'})),ideas=Array.from({length:200},(_,i)=>({id:`i${i}`,status:'IDEA',title:`Idea ${i}`})),messages=Array.from({length:1000},(_,i)=>({messageId:`m${i}`,text:'message',senderName:'A'})),documents=Array.from({length:100},(_,i)=>({id:`d${i}`})),conflicts=Array.from({length:20},(_,i)=>({conflictId:`c${i}`,recordId:`e${i}`,status:'OPEN',type:'SAME_FIELD_CONFLICT',field:'title'})),measure=fn=>{const start=performance.now();fn();return Math.max(1,Math.round(performance.now()-start))};return{agenda_ms:measure(()=>audit({items,documents,travelers:[]})),ideas_ms:measure(()=>ideas.filter(x=>x.title.includes('1'))),budget_ms:measure(()=>calculateTripBudget('t',items)),chat_ms:measure(()=>renderChat({messages,activeConversation:{}})),documents_ms:measure(()=>renderDocuments(true)),admin_ms:measure(()=>renderAdmin({conflicts,devices:[],restoreRequests:[]},{deviceId:'d',deviceState:'TRUSTED'}))}});expect(boot_ms).toBeGreaterThan(0);expect(result.agenda_ms).toBeLessThan(300);expect(result.ideas_ms).toBeLessThan(300);expect(result.budget_ms).toBeLessThan(300);expect(result.chat_ms).toBeLessThan(300);expect(result.documents_ms).toBeLessThan(300);expect(result.admin_ms).toBeLessThan(300);});
