import {test,expect} from '@playwright/test';
const base='http://127.0.0.1:5055';
const post=(path,body)=>fetch(`${base}${path}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}).then(async r=>({statusCode:r.status,body:await r.json()}));
const op=(operationId,recordId,action,baseVersion,changes,userId)=>post('/changes',{operationId,tripId:'trip-italy-2026',recordType:'AGENDA_ENTRY',recordId,action,baseVersion,changes,userId,deviceId:`device-${userId}`,createdAt:new Date().toISOString()});
async function conflict(recordId='conflict-record'){await fetch(`${base}/reset`,{method:'POST'});await op(`create-${recordId}`,recordId,'CREATE',0,{title:'Tren a Milán',startTime:'09:00',location:'Station X'},'seed');await op(`a-${recordId}`,recordId,'UPDATE',1,{startTime:'10:00'},'jonathan');await op(`b-${recordId}`,recordId,'UPDATE',1,{startTime:'11:00'},'jennifer');return (await fetch(`${base}/conflicts?tripId=trip-italy-2026`).then(r=>r.json()))[0];}

test('same-field resolution choices create one resolved canonical version',async()=>{const c=await conflict();const resolved=await post(`/conflicts/${c.conflictId}/resolve`,{resolutionType:'USE_INCOMING',resolverUserId:'jonathan',resolverDeviceId:'admin-device',resolverRole:'ADMIN'});expect(resolved.body).toMatchObject({status:'RESOLVED',canonical:{version:3,data:{startTime:'11:00'}}});expect((await fetch(`${base}/conflicts?tripId=trip-italy-2026`).then(r=>r.json()))[0]).toMatchObject({status:'RESOLVED',resolutionType:'USE_INCOMING',resolvedByUserId:'jonathan'});const duplicate=await post(`/conflicts/${c.conflictId}/resolve`,{resolutionType:'USE_CURRENT',resolverUserId:'jonathan',resolverDeviceId:'admin-device',resolverRole:'ADMIN'});expect(duplicate.body.status).toBe('DUPLICATE');expect(duplicate.body.canonical.version).toBe(3);});

test('manual and current resolutions are explicit',async()=>{let c=await conflict('manual-record');let r=await post(`/conflicts/${c.conflictId}/resolve`,{resolutionType:'MANUAL',resolvedValue:'10:30',resolutionNote:'Horario confirmado',resolverUserId:'jonathan',resolverDeviceId:'admin-device',resolverRole:'ADMIN'});expect(r.body.canonical.data.startTime).toBe('10:30');c=await conflict('current-record');r=await post(`/conflicts/${c.conflictId}/resolve`,{resolutionType:'USE_CURRENT',resolverUserId:'jonathan',resolverDeviceId:'admin-device',resolverRole:'ADMIN'});expect(r.body.canonical.data.startTime).toBe('10:00');});

test('delete/edit keep-deleted and restore are explicit',async()=>{const recordId='delete-resolution';await fetch(`${base}/reset`,{method:'POST'});await op('create-delete',recordId,'CREATE',0,{title:'Tren',startTime:'09:00'},'seed');await op('delete-delete',recordId,'DELETE',1,{},'jonathan');await op('edit-delete',recordId,'UPDATE',1,{title:'Tren cambiado'},'jennifer');let c=(await fetch(`${base}/conflicts?tripId=trip-italy-2026`).then(r=>r.json()))[0];let r=await post(`/conflicts/${c.conflictId}/resolve`,{resolutionType:'KEEP_DELETED',resolverUserId:'jonathan',resolverDeviceId:'admin-device',resolverRole:'ADMIN'});expect(r.body.canonical.deletedAt).toBeTruthy();await fetch(`${base}/reset`,{method:'POST'});await op('create-restore',recordId,'CREATE',0,{title:'Tren',startTime:'09:00'},'seed');await op('delete-restore',recordId,'DELETE',1,{},'jonathan');await op('edit-restore',recordId,'UPDATE',1,{title:'Tren restaurado'},'jennifer');c=(await fetch(`${base}/conflicts?tripId=trip-italy-2026`).then(r=>r.json()))[0];r=await post(`/conflicts/${c.conflictId}/resolve`,{resolutionType:'RESTORE_WITH_EDIT',resolverUserId:'jonathan',resolverDeviceId:'admin-device',resolverRole:'ADMIN'});expect(r.body.canonical).toMatchObject({deletedAt:null,version:3,data:{title:'Tren restaurado'},resolutionEvent:'RESTORE_WITH_EDIT'});});

test('viewer is denied and admin UI resolves an open conflict',async({page})=>{const c=await conflict('ui-record');await page.goto('/');await page.evaluate(()=>{localStorage.setItem('agenda-viajera.role','VIEWER');});const denied=await page.evaluate(async id=>{try{const{resolveConflict}=await import('/src/controllers/conflictController.js');await resolveConflict({conflictId:id,resolutionType:'USE_INCOMING'});return'allowed'}catch(e){return e.message}},c.conflictId);expect(denied).toBe('DENIED');await page.evaluate(()=>localStorage.setItem('agenda-viajera.role','ADMIN'));await page.reload();await page.getByRole('button',{name:'J'}).click();await page.getByText('Administración').click();await expect(page.getByText('Conflictos: 1')).toBeVisible();await page.locator(`[data-conflict-id="${c.conflictId}"] [data-action="conflict-use-incoming"]`).click();await expect(page.getByText('Conflictos: 0')).toBeVisible();await expect(page.getByText(/Resuelto por/)).toBeVisible();});
