import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
const env=Object.fromEntries(readFileSync('.env.test.local','utf8').split(/\r?\n/).filter(x=>x&&!x.trim().startsWith('#')).map(x=>{const i=x.indexOf('=');return [x.slice(0,i).trim(),x.slice(i+1).trim()]}));
test('functional map photos chat surfaces',async({page})=>{
  const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:5003/');
  await page.locator('input[name="email"]').fill(env.SUPABASE_TEST_ADMIN_EMAIL);
  await page.locator('input[name="password"]').fill(env.SUPABASE_TEST_ADMIN_PASSWORD);
  await page.getByRole('button',{name:'Iniciar sesión'}).click();
  await expect(page.locator('.topbar')).toBeVisible({timeout:20000});
  await page.locator('[data-view="map"]').first().click();
  await expect(page.locator('h2',{hasText:'Mapa'})).toBeVisible();
  await expect(page.getByText('Sin ubicación en mapa')).toBeVisible();
  await expect(page.getByRole('button',{name:'Mi ubicación'})).toBeVisible();
  for(const f of ['Todos','Hospedaje','Transporte','Actividades','Comida','Compras']) await expect(page.getByRole('button',{name:f,exact:true})).toBeVisible();
  await page.locator('[data-view="photos"]').first().click();
  await expect(page.locator('h2',{hasText:'Fotos'})).toBeVisible();
  await page.locator('[data-photo-file]').setInputFiles({name:'trip.jpg',mimeType:'image/jpeg',buffer:Buffer.from('fake-image')});
  await page.locator('[data-photo-form] input[name="caption"]').fill('Roma');
  await page.getByRole('button',{name:'Guardar foto'}).click();
  await expect(page.getByText('LOCAL_ONLY')).toBeVisible();
  await page.getByText('Editar metadata').click();
  await page.locator('[data-photo-edit] input[name="caption"]').fill('Roma editada');
  await page.locator('[data-photo-edit]').getByRole('button',{name:'Guardar metadata'}).click();
  await expect(page.getByText('Roma editada')).toBeVisible();
  await page.locator('[data-view="chat"]').first().click();
  await expect(page.locator('h2',{hasText:'Chat del viaje'})).toBeVisible();
  await expect(page.getByLabel('Mensaje')).toBeEnabled();
  await expect(page.getByRole('button',{name:'Directos'})).toBeVisible();
  await page.context().setOffline(true);
  await page.getByLabel('Mensaje').fill('TM3-102 offline functional message');
  await page.getByRole('button',{name:'Enviar'}).click();
  await expect(page.getByText('Pendiente')).toBeVisible();
  await page.context().setOffline(false);
  await page.evaluate(()=>window.__tm3Chat.syncPendingMessages());
  await expect(page.getByText('Enviado')).toBeVisible({timeout:20000});
  await page.getByRole('button',{name:'Directos'}).click();
  await expect(page.locator('[data-chat-ready="true"]')).toBeVisible();
  expect(errors).toEqual([]);
});
