import {test,expect} from '@playwright/test';import {analyzeDay} from '../public/src/services/timeline.js';import {audit} from '../public/src/services/audit.js';import {mergeRecords,createTombstone} from '../public/src/sync/foundation.js';import {MockRemoteSyncAdapter} from '../public/src/services/remoteSyncAdapter.js';import {calculateTripBudget} from '../public/src/services/budget.js';
test('timeline normal gap',()=>expect(analyzeDay([{id:'a',date:'2026-01-01',startTime:'09:00',endTime:'10:00'},{id:'b',date:'2026-01-01',startTime:'11:00',endTime:'12:00'}])[0].type).toBe('NORMAL'));
test('timeline short gap',()=>expect(analyzeDay([{id:'a',date:'2026-01-01',startTime:'09:00',endTime:'10:00'},{id:'b',date:'2026-01-01',startTime:'10:20',endTime:'12:00'}])[0].type).toBe('SHORT_WARNING'));
test('timeline overlap',()=>expect(analyzeDay([{id:'a',date:'2026-01-01',startTime:'09:00',endTime:'11:00'},{id:'b',date:'2026-01-01',startTime:'10:00',endTime:'12:00'}])[0].type).toBe('OVERLAP'));
test('timeline ignores entries without complete times',()=>expect(analyzeDay([{id:'a'},{id:'b',startTime:'10:00'}])).toHaveLength(0));
test('budget separates EUR',()=>expect(calculateTripBudget('t',[{tripId:'t',amount:20,currency:'EUR',costType:'EXACT'}]).byCurrency.EUR).toBe(20));
test('budget separates CHF',()=>expect(calculateTripBudget('t',[{tripId:'t',amount:30,currency:'CHF',costType:'ESTIMATED'}]).byCurrency.CHF).toBe(30));
test('budget estimated total',()=>expect(calculateTripBudget('t',[{tripId:'t',amount:30,costType:'ESTIMATED'}]).estimated).toBe(30));
test('budget unknown count',()=>expect(calculateTripBudget('t',[{tripId:'t',costType:'UNKNOWN'}]).unknownCount).toBe(1));
test('budget paid total',()=>expect(calculateTripBudget('t',[{tripId:'t',amount:30,paid:15,paymentStatus:'PAID'}]).paid).toBe(15));
test('budget category grouping',()=>expect(calculateTripBudget('t',[{tripId:'t',type:'FOOD',amount:9}]).byCategory.FOOD).toBe(9));
test('audit missing date',()=>expect(audit({items:[{id:'x',status:'AGENDA'}]}).some(x=>x.code==='CONFIRMED_WITHOUT_DATE')).toBe(true));
test('audit paid reference',()=>expect(audit({items:[{id:'x',status:'AGENDA',paymentStatus:'PAID'}]}).some(x=>x.code==='PAID_WITHOUT_REFERENCE')).toBe(true));
test('audit unknown cost',()=>expect(audit({items:[{id:'x',status:'AGENDA',costType:'UNKNOWN'}]}).some(x=>x.code==='UNKNOWN_COST')).toBe(true));
test('audit missing travelers',()=>expect(audit({items:[{id:'x',status:'AGENDA',expectedTravelers:2}],travelers:[{entryId:'x'}]}).some(x=>x.code==='MISSING_TRAVELER_DOCUMENTATION')).toBe(true));
test('audit missing document',()=>expect(audit({items:[{id:'x',status:'AGENDA',expectedDocument:true}],documents:[]}).some(x=>x.code==='MISSING_EXPECTED_DOCUMENT')).toBe(true));
test('audit duplicate',()=>expect(audit({items:[{id:'x',title:'Same'},{id:'y',title:'Same'}]}).some(x=>x.code==='POSSIBLE_DUPLICATE')).toBe(true));
test('audit structured issue fields',()=>expect(audit({items:[{id:'x',status:'AGENDA'}]})[0]).toHaveProperty('repairClass'));
test('merge equal fields',()=>expect(mergeRecords({a:1},{a:2},{a:2}).conflicts).toHaveLength(0));
test('merge base local unchanged',()=>expect(mergeRecords({a:1,b:1},{a:2,b:1},{a:1,b:3}).result).toEqual({a:2,b:3}));
test('merge reports local and remote values',()=>expect(mergeRecords({a:1},{a:2},{a:3}).conflicts[0]).toMatchObject({left:2,right:3}));
test('tombstone preserves record identity',()=>expect(createTombstone({id:'x',version:2},'device-a')).toMatchObject({recordId:'x',deletedByDevice:'device-a',version:3}));
test('remote adapter pushes operations',async()=>{const r=new MockRemoteSyncAdapter();await r.pushOperations([{operationId:'1'}]);expect((await r.pullChanges())).toHaveLength(1)});
test('remote adapter registers device',async()=>{const r=new MockRemoteSyncAdapter();await r.registerDevice({deviceId:'a'});expect(r.devices.has('a')).toBe(true)});
test('remote adapter revokes device',async()=>{const r=new MockRemoteSyncAdapter();await r.registerDevice({deviceId:'a',state:'TRUSTED'});await r.revokeDevice('a');expect(r.devices.get('a').state).toBe('REVOKED')});
test('remote adapter conflict resolution',async()=>{const r=new MockRemoteSyncAdapter();expect((await r.submitConflictResolution({recordId:'x'})).status).toBe('RESOLVED')});
test('budget excludes cancelled refunded',()=>expect(calculateTripBudget('t',[{tripId:'t',status:'CANCELLED',refundStatus:'REFUNDED',amount:12}]).plannedExact).toBe(0));
test('budget includes pending refund',()=>expect(calculateTripBudget('t',[{tripId:'t',status:'CANCELLED',refundStatus:'PENDING',amount:12}]).plannedExact).toBe(12));
test('audit issue has trip id',()=>expect(audit({items:[{id:'x',tripId:'t',status:'AGENDA'}]})[0].tripId).toBe('t'));
test('timeline sorts chronologically',()=>expect(analyzeDay([{id:'b',date:'2026-01-01',startTime:'11:00',endTime:'12:00'},{id:'a',date:'2026-01-01',startTime:'09:00',endTime:'10:00'}])[0].from).toBe('a'));
test('remote adapter stale pull starts empty',async()=>{const r=new MockRemoteSyncAdapter();expect(await r.pullChanges()).toEqual([])});
