import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';

const env=Object.fromEntries(readFileSync(resolve(process.cwd(),'.env.test.local'),'utf8').split(/\r?\n/).filter(line=>line&&!line.trim().startsWith('#')).map(line=>{const i=line.indexOf('=');return [line.slice(0,i).trim(),line.slice(i+1).trim()] }));
const credentials={admin:{email:env.SUPABASE_TEST_ADMIN_EMAIL,password:env.SUPABASE_TEST_ADMIN_PASSWORD},traveler:{email:env.SUPABASE_TEST_TRAVELER_EMAIL,password:env.SUPABASE_TEST_TRAVELER_PASSWORD},viewer:{email:env.SUPABASE_TEST_VIEWER_EMAIL,password:env.SUPABASE_TEST_VIEWER_PASSWORD},outsider:{email:env.SUPABASE_TEST_OUTSIDER_EMAIL,password:env.SUPABASE_TEST_OUTSIDER_PASSWORD}};
for(const [role,value] of Object.entries(credentials))if(!value.email||!value.password)throw Error(`Missing Supabase test credentials for ${role}`);
const tripId='11111111-1111-4111-8111-111111111100';
const recordId='11111111-1111-4111-8111-111111111101';
const tombstoneId='11111111-1111-4111-8111-111111111102';

async function openUser(browser,role){const context=await browser.newContext();const page=await context.newPage();await page.goto('/');const user=await page.evaluate(async({email,password})=>{const{signInWithEmailPassword}=await import('/src/supabaseClient.js');const{data,error}=await signInWithEmailPassword(email,password);if(error)throw Error(`Supabase sign-in failed for test role: ${error.message}`);return{id:data.user.id,email:data.user.email}},credentials[role]);return{context,page,user,role}}
async function run(page,fn,args={}){return page.evaluate(fn,args)}
async function ensureProfile(actor,displayName){return run(actor.page,async({id,email,displayName})=>{const{getSupabaseClient}=await import('/src/supabaseClient.js');const c=await getSupabaseClient();const existing=await c.from('av_users').select('id').eq('id',id).maybeSingle();if(existing.error)throw Error(`profile lookup ${existing.error.code||''}: ${existing.error.message||JSON.stringify(existing.error)}`);if(!existing.data){const{error}=await c.from('av_users').insert({id,display_name:displayName,email});if(error)throw Error(`profile insert ${error.code||''}: ${error.message||JSON.stringify(error)}`);}return id},{id:actor.user.id,email:actor.user.email,displayName})}
async function adapter(actor){return run(actor.page,async({deviceId,userId})=>{const{SupabaseRemoteSyncAdapter}=await import('/src/sync/SupabaseRemoteSyncAdapter.js');return{adapter:new SupabaseRemoteSyncAdapter({deviceId,userId})}}, {deviceId:`tm3-live-${actor.role}`,userId:actor.user.id})}

test('authenticated Supabase sandbox validates Auth, RLS, sync, chat and devices',async({browser})=>{const actors={admin:await openUser(browser,'admin'),traveler:await openUser(browser,'traveler'),viewer:await openUser(browser,'viewer'),outsider:await openUser(browser,'outsider')};try{
  for(const [role,actor] of Object.entries(actors))await ensureProfile(actor,`Agenda Viajera ${role} Test`);
  await run(actors.admin.page,async({tripId,adminId})=>{const{getSupabaseClient}=await import('/src/supabaseClient.js');const c=await getSupabaseClient();const existing=await c.from('av_trips').select('id').eq('id',tripId).maybeSingle();if(existing.error)throw existing.error;if(!existing.data){const{error}=await c.from('av_trips').insert({id:tripId,name:'Agenda Viajera Integration Test',status:'PLANNING',created_by:adminId});if(error)throw error;}const membership=await c.from('av_trip_memberships').select('id').eq('trip_id',tripId).eq('user_id',adminId).maybeSingle();if(membership.error)throw membership.error;if(!membership.data){const{error}=await c.from('av_trip_memberships').insert({trip_id:tripId,user_id:adminId,role:'ADMIN',permissions:{CanChat:true,CanEditAgenda:true,CanViewDocuments:true,CanResolveConflicts:true}});if(error)throw error;}},{tripId,adminId:actors.admin.user.id});
  for(const role of ['traveler','viewer'])await run(actors.admin.page,async({tripId,userId,role})=>{const{getSupabaseClient}=await import('/src/supabaseClient.js');const c=await getSupabaseClient();const existing=await c.from('av_trip_memberships').select('id').eq('trip_id',tripId).eq('user_id',userId).maybeSingle();if(existing.error)throw existing.error;if(!existing.data){const permissions=role==='traveler'?{CanChat:true,CanEditAgenda:true,CanViewDocuments:true}:{CanChat:false,CanEditAgenda:false,CanViewDocuments:false};const{error}=await c.from('av_trip_memberships').insert({trip_id:tripId,user_id:userId,role:role==='traveler'?'TRAVELER':'VIEWER',permissions});if(error)throw error;}},{tripId,userId:actors[role].user.id,role});
  const viewerTrip=await run(actors.viewer.page,async({tripId})=>{const{getSupabaseClient}=await import('/src/supabaseClient.js');const{data,error}=await (await getSupabaseClient()).from('av_trips').select('id').eq('id',tripId);if(error)throw error;return data.length},{tripId});expect(viewerTrip).toBe(1);
  for(const role of ['admin','traveler','viewer','outsider'])await run(actors[role].page,async({deviceId,userId})=>{const{getSupabaseClient}=await import('/src/supabaseClient.js');const c=await getSupabaseClient();const existing=await c.from('av_devices').select('device_id').eq('device_id',deviceId).maybeSingle();if(existing.error)throw existing.error;if(!existing.data){const{error}=await c.from('av_devices').insert({device_id:deviceId,user_id:userId,state:'TRUSTED',name:`TM3 live ${deviceId}`});if(error)throw error;}},{deviceId:`tm3-live-${role}`,userId:actors[role].user.id});
  await run(actors.admin.page,async({recordId,tripId})=>{const{getSupabaseClient}=await import('/src/supabaseClient.js');const c=await getSupabaseClient();await c.from('av_records').delete().eq('record_id',recordId);await c.from('av_records').delete().eq('record_id','11111111-1111-4111-8111-111111111102');await c.from('av_documents').delete().eq('trip_id',tripId);},{recordId,tripId});
  const created=await run(actors.admin.page,async({tripId,recordId,userId})=>{const{SupabaseRemoteSyncAdapter}=await import('/src/sync/SupabaseRemoteSyncAdapter.js');const a=new SupabaseRemoteSyncAdapter({deviceId:'tm3-live-admin',userId});const[r]=await a.pushOperations([{operationId:crypto.randomUUID(),tripId,recordType:'AGENDA_ENTRY',recordId,action:'CREATE',baseVersion:0,changes:{title:'Initial',startTime:'09:00'},userId,deviceId:'tm3-live-admin'}]);return r},{tripId,recordId,userId:actors.admin.user.id});expect(created.status).toBe('APPLIED');
  const updated=await run(actors.admin.page,async({tripId,recordId,userId})=>{const{SupabaseRemoteSyncAdapter}=await import('/src/sync/SupabaseRemoteSyncAdapter.js');const a=new SupabaseRemoteSyncAdapter({deviceId:'tm3-live-admin',userId});const[r]=await a.pushOperations([{operationId:crypto.randomUUID(),tripId,recordType:'AGENDA_ENTRY',recordId,action:'UPDATE',baseVersion:1,changes:{title:'Current'},userId,deviceId:'tm3-live-admin'}]);return r},{tripId,recordId,userId:actors.admin.user.id});expect(updated.status).toBe('APPLIED');
  const merged=await run(actors.traveler.page,async({tripId,recordId,userId})=>{const{SupabaseRemoteSyncAdapter}=await import('/src/sync/SupabaseRemoteSyncAdapter.js');const a=new SupabaseRemoteSyncAdapter({deviceId:'tm3-live-traveler',userId});const[r]=await a.pushOperations([{operationId:crypto.randomUUID(),tripId,recordType:'AGENDA_ENTRY',recordId,action:'UPDATE',baseVersion:1,changes:{place:'Milan'},userId,deviceId:'tm3-live-traveler'}]);return r},{tripId,recordId,userId:actors.traveler.user.id});expect(merged.status).toBe('APPLIED');
  const conflict=await run(actors.traveler.page,async({tripId,recordId,userId})=>{const{SupabaseRemoteSyncAdapter}=await import('/src/sync/SupabaseRemoteSyncAdapter.js');const a=new SupabaseRemoteSyncAdapter({deviceId:'tm3-live-traveler',userId});const[r]=await a.pushOperations([{operationId:crypto.randomUUID(),tripId,recordType:'AGENDA_ENTRY',recordId,action:'UPDATE',baseVersion:1,changes:{title:'Incoming'},userId,deviceId:'tm3-live-traveler'}]);return r},{tripId,recordId,userId:actors.traveler.user.id});expect(conflict.status).toBe('CONFLICT');
  const viewerResolve=await run(actors.viewer.page,async({conflictId,userId})=>{try{const{SupabaseRemoteSyncAdapter}=await import('/src/sync/SupabaseRemoteSyncAdapter.js');await new SupabaseRemoteSyncAdapter({deviceId:'tm3-live-viewer',userId}).resolveConflict({conflictId,resolutionType:'USE_INCOMING',resolverUserId:userId,resolverDeviceId:'tm3-live-viewer'});return false}catch{return true}},{conflictId:conflict.conflictId,userId:actors.viewer.user.id});expect(viewerResolve).toBe(true);
  const resolved=await run(actors.admin.page,async({conflictId,userId})=>{const{SupabaseRemoteSyncAdapter}=await import('/src/sync/SupabaseRemoteSyncAdapter.js');return new SupabaseRemoteSyncAdapter({deviceId:'tm3-live-admin',userId}).resolveConflict({conflictId,resolutionType:'USE_INCOMING',resolverUserId:userId,resolverDeviceId:'tm3-live-admin'})},{conflictId:conflict.conflictId,userId:actors.admin.user.id});expect(resolved.status).toBe('RESOLVED');
  const tombstoneCreated=await run(actors.admin.page,async({tripId,recordId,userId})=>{const{SupabaseRemoteSyncAdapter}=await import('/src/sync/SupabaseRemoteSyncAdapter.js');const[r]=await new SupabaseRemoteSyncAdapter({deviceId:'tm3-live-admin',userId}).pushOperations([{operationId:crypto.randomUUID(),tripId,recordType:'AGENDA_ENTRY',recordId,action:'CREATE',baseVersion:0,changes:{title:'Delete me'},userId,deviceId:'tm3-live-admin'}]);return r},{tripId,recordId:tombstoneId,userId:actors.admin.user.id});expect(tombstoneCreated.status).toBe('APPLIED');
  const tombstoneDeleted=await run(actors.admin.page,async({tripId,recordId,userId})=>{const{SupabaseRemoteSyncAdapter}=await import('/src/sync/SupabaseRemoteSyncAdapter.js');const[r]=await new SupabaseRemoteSyncAdapter({deviceId:'tm3-live-admin',userId}).pushOperations([{operationId:crypto.randomUUID(),tripId,recordType:'AGENDA_ENTRY',recordId,action:'DELETE',baseVersion:1,changes:{},userId,deviceId:'tm3-live-admin'}]);return r},{tripId,recordId:tombstoneId,userId:actors.admin.user.id});expect(tombstoneDeleted.status).toBe('APPLIED');
  const tombstoneConflict=await run(actors.traveler.page,async({tripId,recordId,userId})=>{const{SupabaseRemoteSyncAdapter}=await import('/src/sync/SupabaseRemoteSyncAdapter.js');const[r]=await new SupabaseRemoteSyncAdapter({deviceId:'tm3-live-traveler',userId}).pushOperations([{operationId:crypto.randomUUID(),tripId,recordType:'AGENDA_ENTRY',recordId,action:'UPDATE',baseVersion:1,changes:{title:'Resurrect me'},userId,deviceId:'tm3-live-traveler'}]);return r},{tripId,recordId:tombstoneId,userId:actors.traveler.user.id});expect(tombstoneConflict.status).toBe('CONFLICT');
  const tombstoneResolved=await run(actors.admin.page,async({conflictId,userId})=>{const{SupabaseRemoteSyncAdapter}=await import('/src/sync/SupabaseRemoteSyncAdapter.js');return new SupabaseRemoteSyncAdapter({deviceId:'tm3-live-admin',userId}).resolveConflict({conflictId,resolutionType:'KEEP_DELETED',resolverUserId:userId,resolverDeviceId:'tm3-live-admin'})},{conflictId:tombstoneConflict.conflictId,userId:actors.admin.user.id});expect(tombstoneResolved.status).toBe('RESOLVED');
  const tombstoneRecord=await run(actors.admin.page,async({recordId})=>{const{getSupabaseClient}=await import('/src/supabaseClient.js');const{data,error}=await (await getSupabaseClient()).from('av_records').select('deleted_at').eq('record_id',recordId).single();if(error)throw error;return data},{recordId:tombstoneId});expect(tombstoneRecord.deleted_at).toBeTruthy();
  const outsider=await run(actors.outsider.page,async({tripId})=>{const{getSupabaseClient}=await import('/src/supabaseClient.js');const{data,error}=await (await getSupabaseClient()).from('av_trips').select('id').eq('id',tripId);return{count:data?.length||0,error:Boolean(error)}},{tripId});expect(outsider.count).toBe(0);
  const viewerWrite=await run(actors.viewer.page,async({tripId,recordId})=>{const{getSupabaseClient}=await import('/src/supabaseClient.js');const{error}=await (await getSupabaseClient()).from('av_records').insert({record_id:crypto.randomUUID(),trip_id:tripId,record_type:'AGENDA_ENTRY',data:{}});return Boolean(error)},{tripId,recordId});expect(viewerWrite).toBe(true);
  const doc=await run(actors.admin.page,async({tripId,userId})=>{const{getSupabaseClient}=await import('/src/supabaseClient.js');const{data,error}=await (await getSupabaseClient()).from('av_documents').insert({trip_id:tripId,title:'TM3 sandbox metadata',category:'TEST',created_by:userId}).select('document_id').single();if(error)throw error;return data.document_id},{tripId,userId:actors.admin.user.id});
  const viewerDocs=await run(actors.viewer.page,async({tripId})=>{const{getSupabaseClient}=await import('/src/supabaseClient.js');const{data,error}=await (await getSupabaseClient()).from('av_documents').select('document_id').eq('trip_id',tripId);return{count:data?.length||0,error:Boolean(error)}},{tripId});expect(viewerDocs.count).toBe(0);
  const group=await run(actors.admin.page,async({tripId,userId})=>{const{SupabaseRemoteSyncAdapter}=await import('/src/sync/SupabaseRemoteSyncAdapter.js');return new SupabaseRemoteSyncAdapter({deviceId:'tm3-live-admin',userId}).sendMessage({messageId:crypto.randomUUID(),tripId,conversationId:`group:${tripId}`,conversationType:'GROUP',senderUserId:userId,text:'sandbox group'})},{tripId,userId:actors.admin.user.id});expect(group.messageId).toBeTruthy();
  const travelerGroup=await run(actors.traveler.page,async({tripId,userId})=>{const{SupabaseRemoteSyncAdapter}=await import('/src/sync/SupabaseRemoteSyncAdapter.js');return new SupabaseRemoteSyncAdapter({deviceId:'tm3-live-traveler',userId}).listMessages({tripId,conversationId:`group:${tripId}`,userId})},{tripId,userId:actors.traveler.user.id});expect(travelerGroup.length).toBeGreaterThan(0);
  const direct=await run(actors.admin.page,async({tripId,userId,recipientUserId})=>{const{SupabaseRemoteSyncAdapter}=await import('/src/sync/SupabaseRemoteSyncAdapter.js');return new SupabaseRemoteSyncAdapter({deviceId:'tm3-live-admin',userId}).sendMessage({messageId:crypto.randomUUID(),tripId,conversationId:'direct:admin-traveler',conversationType:'DIRECT',senderUserId:userId,recipientUserId,text:'private sandbox'})},{tripId,userId:actors.admin.user.id,recipientUserId:actors.traveler.user.id});const thirdDirect=await run(actors.viewer.page,async({tripId,userId})=>{const{SupabaseRemoteSyncAdapter}=await import('/src/sync/SupabaseRemoteSyncAdapter.js');return new SupabaseRemoteSyncAdapter({deviceId:'tm3-live-viewer',userId}).listMessages({tripId,conversationId:'direct:admin-traveler',userId})},{tripId,userId:actors.viewer.user.id});expect(direct.messageId).toBeTruthy();expect(thirdDirect).toHaveLength(0);
  const commandId=await run(actors.admin.page,async({deviceId})=>{const{getSupabaseClient}=await import('/src/supabaseClient.js');const{data,error}=await (await getSupabaseClient()).from('av_device_commands').insert({device_id:deviceId,command_type:'CLOSE_SESSION',payload:{source:'TM3-067'}}).select('id').single();if(error)throw error;return data.id},{deviceId:'tm3-live-traveler'});const commands=await run(actors.traveler.page,async({deviceId,userId})=>{const{SupabaseRemoteSyncAdapter}=await import('/src/sync/SupabaseRemoteSyncAdapter.js');const a=new SupabaseRemoteSyncAdapter({deviceId,userId});const rows=await a.getDeviceCommands(deviceId);if(rows[0])await a.completeDeviceCommand(rows[0].id);return rows},{deviceId:'tm3-live-traveler',userId:actors.traveler.user.id});expect(commands.some(x=>x.id===commandId)).toBe(true);
  const restore=await run(actors.traveler.page,async({deviceId,userId})=>{const{SupabaseRemoteSyncAdapter}=await import('/src/sync/SupabaseRemoteSyncAdapter.js');return new SupabaseRemoteSyncAdapter({deviceId,userId}).createRestoreRequest({deviceId,userId,reason:'TM3 authenticated sandbox restore request'})},{deviceId:'tm3-live-traveler',userId:actors.traveler.user.id});expect(restore.status).toBe('PENDING');
  const restoreResolved=await run(actors.admin.page,async({id,adminUserId})=>{const{SupabaseRemoteSyncAdapter}=await import('/src/sync/SupabaseRemoteSyncAdapter.js');const a=new SupabaseRemoteSyncAdapter({deviceId:'tm3-live-admin',userId:adminUserId});const requests=await a.listRestoreRequests();const request=requests.find(x=>x.id===id);if(!request)throw Error('restore request not visible to admin');return a.resolveRestoreRequest(id,{status:'APPROVED',resolutionNote:'TM3 live sandbox approved',resolvedBy:adminUserId})},{id:restore.id,adminUserId:actors.admin.user.id});expect(restoreResolved.status).toBe('APPROVED');
}finally{for(const actor of Object.values(actors))await actor.context.close()}});
