import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
const env=Object.fromEntries(readFileSync('.env.test.local','utf8').split(/\r?\n/).filter(x=>x&&!x.trim().startsWith('#')).map(x=>{const i=x.indexOf('=');return [x.slice(0,i).trim(),x.slice(i+1).trim()]}));
const tripId='1aafae82-4ff7-423b-ade2-25170e8b0dd4';
test('real QR item/traveler save, sync, reload, offline render and purge contract',async({page})=>{await page.goto('/');const result=await page.evaluate(async({email,password,tripId})=>{
  const auth=await (await import('/src/supabaseClient.js')).signInWithEmailPassword(email,password);if(auth.error)throw auth.error;const userId=auth.data.user.id,deviceId=`tm3-qr-${crypto.randomUUID()}`;localStorage.setItem('agenda-viajera.user',userId);localStorage.setItem('agenda-viajera.role','ADMIN');localStorage.setItem('agenda-viajera.device',deviceId);localStorage.setItem('agenda-viajera.remoteMode','supabase');
  const {SupabaseRemoteSyncAdapter}=await import('/src/sync/SupabaseRemoteSyncAdapter.js');const {platformRepository}=await import('/src/services/localPlatform.js');const {createLocalRepository}=await import('/src/db/localRepository.js');const {createAgendaController}=await import('/src/controllers/agendaController.js');const {flushPendingOperations}=await import('/src/controllers/mutationController.js');const {qrSvg}=await import('/src/services/qrCapture.js');
  const adapter=new SupabaseRemoteSyncAdapter({userId,deviceId});const records=await adapter.pullRecords({tripId});const target=records.find(r=>r.recordType==='LODGING'&&Array.isArray(r.data?.passengers)&&r.data.passengers.length>=2)||records.find(r=>Array.isArray(r.data?.passengers));if(!target)throw Error('No traveler-capable canonical item');const before=await adapter.getRecord(target.recordId),original={qrPayload:before.data?.qrPayload||'',passengers:before.data?.passengers||[]};const rootRepo=await platformRepository();await rootRepo.applyCanonical(before);const repo=createLocalRepository();await repo.ready;const access={permissions:{edit:true}};const agenda=createAgendaController({repository:repo,access});const item=repo.snapshot().items.find(x=>x.id===target.recordId)||{...before.data,id:target.recordId,version:before.version};const itemPayload='TM3-SYNTHETIC-ITEM-QR';const passengerPayload='TM3-SYNTHETIC-PASSENGER-QR';
  await agenda.save(target.recordId,{qrPayload:itemPayload,qrCapturedAt:new Date().toISOString(),qrSourceType:'MANUAL',qrIsDynamic:'UNKNOWN'});await flushPendingOperations();let remote=await adapter.getRecord(target.recordId);if(remote.data.qrPayload!==itemPayload)throw Error('Item QR canonical readback failed');const nextPassengers=(item.passengers||remote.data.passengers||[]).map((p,i)=>i===0?{...p,qrPayload:passengerPayload,qrCapturedAt:new Date().toISOString(),qrSourceType:'CAMERA',qrIsDynamic:'UNKNOWN'}:p);await agenda.save(target.recordId,{passengers:nextPassengers});await flushPendingOperations();remote=await adapter.getRecord(target.recordId);if(remote.data.passengers?.[0]?.qrPayload!==passengerPayload)throw Error('Traveler QR canonical readback failed');const reopened=await createLocalRepository();await reopened.ready;if(reopened.snapshot().items.find(x=>x.id===target.recordId)?.qrPayload!==itemPayload)throw Error('QR local reload failed');const viewer=createAgendaController({repository:reopened,access:{permissions:{edit:false}}});let denied=false;try{await viewer.save(target.recordId,{qrPayload:'DENIED'})}catch{denied=true}if(!denied)throw Error('Viewer QR mutation was allowed');if(!qrSvg(passengerPayload).includes('<svg'))throw Error('Offline QR regeneration failed');await agenda.save(target.recordId,{qrPayload:original.qrPayload,passengers:original.passengers});await flushPendingOperations();remote=await adapter.getRecord(target.recordId);if((remote.data.qrPayload||'')!==original.qrPayload||JSON.stringify(remote.data.passengers||[])!==JSON.stringify(original.passengers))throw Error('QR cleanup revert failed');await rootRepo.put('agendaEntries',{id:'root',data:{items:[{id:'purge',qrPayload:itemPayload,passengers:[{passengerId:'x',qrPayload:passengerPayload}]}],ideas:[]}});await rootRepo.purgeQrData();const purged=await rootRepo.read('agendaEntries','root');if(JSON.stringify(purged).includes('qrPayload'))throw Error('QR purge failed');return{target:target.recordId,itemReadback:true,travelerReadback:true,queueApplied:true,reload:true,viewerDenied:denied,offline:true,purged:true};
},{email:env.SUPABASE_TEST_ADMIN_EMAIL,password:env.SUPABASE_TEST_ADMIN_PASSWORD,tripId});expect(result).toMatchObject({itemReadback:true,travelerReadback:true,queueApplied:true,reload:true,viewerDenied:true,offline:true,purged:true});});
