import { createClient } from 'npm:@supabase/supabase-js@2.45.4';

const cors = {'Access-Control-Allow-Origin':'https://2110jrv.github.io','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}});
const encoder=new TextEncoder();
const b64=(bytes:Uint8Array)=>btoa(String.fromCharCode(...bytes));
const unb64=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const b64url=(bytes:Uint8Array)=>b64(bytes).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const text=(v:unknown)=>String(v??'');
const safeName=(v:string)=>v.replace(/[^a-zA-Z0-9._-]+/g,'-').slice(0,180)||'photo.jpg';
const tripId=(body:any)=>text(body.tripId||'1aafae82-4ff7-423b-ade2-25170e8b0dd4');
const appKey=()=>Deno.env.get('DROPBOX_APP_KEY')||'';
const appSecret=()=>Deno.env.get('DROPBOX_APP_SECRET')||'';
const redirectUri='https://2110jrv.github.io/TravelManager_3/';
async function key(){const digest=await crypto.subtle.digest('SHA-256',encoder.encode(`tm3-dropbox-refresh:${appSecret()}`));return crypto.subtle.importKey('raw',digest,{name:'AES-GCM'},false,['encrypt','decrypt']);}
async function seal(value:string){const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(),encoder.encode(value));return `${b64(iv)}.${b64(new Uint8Array(data))}`;}
async function open(value:string){const [iv,data]=value.split('.');const bytes=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(iv)},await key(),unb64(data));return new TextDecoder().decode(bytes);}
async function dropbox(path:string,token:string,body?:unknown,bytes?:Uint8Array){const headers:any={'Authorization':`Bearer ${token}`};if(body)headers['Dropbox-API-Arg']=JSON.stringify(body);if(bytes)headers['Content-Type']='application/octet-stream';const r=await fetch(`https://content.dropboxapi.com/2/${path}`,{method:'POST',headers,body:bytes||undefined});const data=await r.json().catch(()=>({}));if(!r.ok)throw Error(`DROPBOX_${r.status}`);return data;}
async function dropboxBinary(path:string,token:string,body:unknown){const r=await fetch(`https://content.dropboxapi.com/2/${path}`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Dropbox-API-Arg':JSON.stringify(body)},body:null});if(!r.ok)throw Error(`DROPBOX_${r.status}`);return {data:b64(new Uint8Array(await r.arrayBuffer())),mime:r.headers.get('content-type')||'image/jpeg'};}
async function api(path:string,token:string,body:unknown){const r=await fetch(`https://api.dropboxapi.com/2/${path}`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok)throw Error(`DROPBOX_${r.status}`);return data;}
async function tokenExchange(code:string,verifier:string){const body=new URLSearchParams({code,grant_type:'authorization_code',client_id:appKey(),client_secret:appSecret(),redirect_uri:redirectUri,code_verifier:verifier});const r=await fetch('https://api.dropboxapi.com/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const data=await r.json().catch(()=>({}));if(!r.ok||!data.refresh_token)throw Error('DROPBOX_OAUTH_FAILED');return data;}
function clients(req:Request){const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const auth=req.headers.get('Authorization')||'';return {caller:createClient(url,anon,{global:{headers:{Authorization:auth}}}),admin:createClient(url,service)};}
async function connection(admin:any,userId:string,trip:string){const {data,error}=await admin.from('av_external_storage_connections').select('*').eq('auth_user_id',userId).eq('trip_id',trip).eq('provider','dropbox').maybeSingle();if(error)throw error;return data;}
async function accessToken(admin:any,row:any){const refresh=await open(row.encrypted_refresh_token);const body=new URLSearchParams({grant_type:'refresh_token',refresh_token:refresh,client_id:appKey(),client_secret:appSecret()});const r=await fetch('https://api.dropboxapi.com/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const data=await r.json().catch(()=>({}));if(!r.ok||!data.access_token)throw Error('DROPBOX_REFRESH_FAILED');return data.access_token;}
async function requireCaller(req:Request){const {caller,admin}=clients(req);const {data:{user}}=await caller.auth.getUser();if(!user)throw Object.assign(Error('AUTH_REQUIRED'),{status:401});return {admin,user};}

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{
  const raw=req.headers.get('content-type')||'';let body:any={};let file:File|null=null;
  if(raw.includes('multipart/form-data')){const form=await req.formData();for(const [k,v] of form.entries()){if(k==='file'&&v instanceof File)file=v;else body[k]=v;}}else body=await req.json();
  const action=text(body.action);
  if(action==='oauth_config')return json({appKey:appKey(),redirectUri});
  const {admin,user}=await requireCaller(req);const trip=tripId(body);
  if(action==='oauth_exchange'){if(!body.code||!body.verifier||!appKey()||!appSecret())throw Error('DROPBOX_NOT_CONFIGURED');const tokens=await tokenExchange(text(body.code),text(body.verifier));const account=await api('users/get_current_account',tokens.access_token,{});const encrypted=await seal(tokens.refresh_token);const saved=await admin.from('av_external_storage_connections').upsert({auth_user_id:user.id,trip_id:trip,provider:'dropbox',provider_account_id:account.account_id,display_name:account.name?.display_name||account.email,encrypted_refresh_token:encrypted,scopes:tokens.scope?text(tokens.scope).split(' '):[],status:'CONNECTED',updated_at:new Date().toISOString()},{onConflict:'auth_user_id,trip_id,provider'}).select('provider_account_id,display_name,status,default_folder_path').single();if(saved.error)throw saved.error;return json({ok:true,connection:saved.data});}
  const row=await connection(admin,user.id,trip);if(action==='status')return json({ok:true,connected:Boolean(row&&row.status==='CONNECTED'),connection:row?{provider_account_id:row.provider_account_id,display_name:row.display_name,status:row.status,default_folder_path:row.default_folder_path}:null});if(!row||row.status!=='CONNECTED')return json({error:'DROPBOX_NOT_CONNECTED'},409);
  const token=await accessToken(admin,row);
  if(action==='resolve_folder'){const metadata=await api('sharing/get_shared_link_metadata',token,{url:body.sharedUrl});const path=text(metadata.path_lower||metadata.path_display||'');if(!path)throw Error('DROPBOX_FOLDER_NOT_FOUND');const saved=await admin.from('av_external_storage_connections').update({default_folder_path:path,updated_at:new Date().toISOString()}).eq('id',row.id).select('default_folder_path').single();if(saved.error)throw saved.error;return json({ok:true,folder:saved.data.default_folder_path});}
  if(action==='disconnect'){const result=await admin.from('av_external_storage_connections').update({status:'DISCONNECTED',encrypted_refresh_token:'',updated_at:new Date().toISOString()}).eq('id',row.id);if(result.error)throw result.error;return json({ok:true});}
  if(action==='upload'){if(!file&&body.base64)file=new File([unb64(text(body.base64))],safeName(text(body.filename)),{type:text(body.mimeType)||'application/octet-stream'});if(!file)throw Error('PHOTO_REQUIRED');const folder=text(row.default_folder_path);if(!folder)throw Error('DROPBOX_FOLDER_NOT_RESOLVED');const date=/^\d{4}-\d{2}-\d{2}$/.test(text(body.date))?text(body.date):new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome'}).format(new Date());const bytes=new Uint8Array(await file.arrayBuffer());const uploaded=await dropbox('files/upload',token,{path:`${folder}/${date}/${safeName(file.name)}`,mode:{'.tag':'add'},autorename:true,mute:true},bytes);const recordId=crypto.randomUUID();const data={id:recordId,tripId:trip,caption:text(body.caption),place:text(body.place),capturedAt:body.capturedAt||new Date().toISOString(),agendaItemId:body.agendaItemId||null,uploader:user.id,state:'UPLOADED',provider:'dropbox',externalId:uploaded.id,externalUrl:uploaded.path_display,dropboxPath:uploaded.path_display,dropboxRev:uploaded.rev,updatedAt:new Date().toISOString()};const stored=await admin.from('av_records').upsert({record_id:recordId,trip_id:trip,record_type:'PHOTO',version:1,data,updated_by_user:user.id},{onConflict:'record_id'});if(stored.error)throw stored.error;let thumbnail=null;try{thumbnail=await dropboxBinary('files/get_thumbnail',token,{path:uploaded.path_lower||uploaded.path_display,format:{'.tag':'jpeg'},size:{'.tag':'w256h256'}})}catch{}return json({ok:true,photo:data,thumbnail});}
  if(action==='list'){const records=await admin.from('av_records').select('record_id,data').eq('trip_id',trip).eq('record_type','PHOTO').is('deleted_at',null).order('updated_at',{ascending:false});if(records.error)throw records.error;return json({ok:true,photos:(records.data||[]).map(x=>x.data)});}
  if(action==='thumbnail'){const meta=await dropboxBinary('files/get_thumbnail',token,{path:body.path,format:{'.tag':'jpeg'},size:{'.tag':'w256h256'}});return json({ok:true,thumbnail:meta});}
  return json({error:'UNKNOWN_ACTION'},400);
}catch(error){const status=(error as any)?.status||500;console.error('[dropbox-photo-storage]',error instanceof Error?error.message:'internal');return json({error:status===401?'AUTH_REQUIRED':'DROPBOX_OPERATION_FAILED'},status);}});
